var searchData=
[
  ['mapdelete_0',['MapDelete',['../_program_8cs.html#aba0d435dcc990a7ed4afaee131cb241a',1,'MapDelete(&quot;/DeleteGame/{id}&quot;,(int id, MyBoardsContext db)=&gt; { var boardGame=db.BoardGames.First(u=&gt; u.Id==id);var comments=db.BoardGameComments.Where(u=&gt; u.BoardGameId==id).ToList();db.RemoveRange(comments);db.Remove(boardGame);db.SaveChanges();}):&#160;Program.cs'],['../_program_8cs.html#a96e50f22ed9c163222dc6eee2658c94a',1,'MapDelete(&quot;/DeleteComment/{id}&quot;,(int id, MyBoardsContext db)=&gt; { var comment=db.BoardGameComments.First(u=&gt; u.Id==id);db.Remove(comment);db.SaveChanges();}):&#160;Program.cs']]],
  ['mapget_1',['MapGet',['../_program_8cs.html#ab6daeb752cf5268b19931a98cf9aae08',1,'MapGet(&quot;View_TopAuthors&quot;,(MyBoardsContext db)=&gt; { var topAuthors=db.ViewTopAuthors.ToList();return topAuthors;}):&#160;Program.cs'],['../_program_8cs.html#a26916e8a538f7b135b9311117d643278',1,'MapGet(&quot;View_MostComments&quot;,(MyBoardsContext db)=&gt; { var MostComments=db.ViewMostComments.ToList();return MostComments;}):&#160;Program.cs'],['../_program_8cs.html#a25ce1cdc8286a3b4b7a4a2eed9372c65',1,'MapGet(&quot;View_NotAvailableGames&quot;,(MyBoardsContext db)=&gt; { var NotAvailableGames=db.ViewNotAvailableGames.ToList();return NotAvailableGames;}):&#160;Program.cs'],['../_program_8cs.html#a51da4b259d930233ec43030a64f20e5e',1,'MapGet(&quot;View_TagGames&quot;,(MyBoardsContext db)=&gt; { var TagGames=db.ViewTagGames.ToList();return TagGames;}):&#160;Program.cs'],['../_program_8cs.html#a9d81c80a0a351b63fc30fd0f9c78ab3f',1,'MapGet(&quot;View_UsersAdres&quot;,(MyBoardsContext db)=&gt; { var UsersAdress=db.ViewUsersAdress.ToList();return UsersAdress;}):&#160;Program.cs'],['../_program_8cs.html#a32dcbd0d431b1e1e42e0d0256e4287e2',1,'MapGet(&quot;Games&quot;,(MyBoardsContext db)=&gt; { var boardGames=db.BoardGames.ToList();return boardGames;}):&#160;Program.cs'],['../_program_8cs.html#ad569fc227780bbd961dc08cef4974b21',1,'MapGet(&quot;/GamesCommentsTags/{id}&quot;,(int id, MyBoardsContext db)=&gt; { var boardGame=db.BoardGames .Include(u=&gt; u.Comments) .Include(h=&gt; h.Tags) .First(u=&gt; u.Id==id);return boardGame;}):&#160;Program.cs']]],
  ['mappost_2',['MapPost',['../_program_8cs.html#a8adb0c8df9e29e10e9e494831b8427b9',1,'Program.cs']]],
  ['mapput_3',['MapPut',['../_program_8cs.html#ad22cbe7f20fc7b010a016d93b07feb6e',1,'Program.cs']]],
  ['message_4',['Message',['../class_rental_board_games_1_1_entities_1_1_board_game_comment.html#a37db39ea4189365945db3e81ea6b30de',1,'RentalBoardGames::Entities::BoardGameComment']]],
  ['mostcomment_5',['MostComment',['../class_rental_board_games_1_1_entities_1_1_view_models_1_1_most_comment.html',1,'RentalBoardGames::Entities::ViewModels']]],
  ['mostcomment_2ecs_6',['MostComment.cs',['../_most_comment_8cs.html',1,'']]],
  ['myboardscontext_7',['MyBoardsContext',['../class_rental_board_games_1_1_entities_1_1_my_boards_context.html#a7e9f3ec0799f88843d3f1eecb597b0c4',1,'RentalBoardGames.Entities.MyBoardsContext.MyBoardsContext()'],['../class_rental_board_games_1_1_entities_1_1_my_boards_context.html',1,'RentalBoardGames.Entities.MyBoardsContext']]],
  ['myboardscontext_2ecs_8',['MyBoardsContext.cs',['../_my_boards_context_8cs.html',1,'']]],
  ['myboardscontextmodelsnapshot_9',['MyBoardsContextModelSnapshot',['../class_rental_board_games_1_1_migrations_1_1_my_boards_context_model_snapshot.html',1,'RentalBoardGames::Migrations']]],
  ['myboardscontextmodelsnapshot_2ecs_10',['MyBoardsContextModelSnapshot.cs',['../_my_boards_context_model_snapshot_8cs.html',1,'']]]
];
